

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/Header/header";

import { Providers } from "./contexts/Provider";
import { Notificatation, NotificationContext, NotificationProvider } from "./contexts/notificationProvider";
import { useContext } from "react";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
      <main>
      <Providers  >
  <NotificationProvider>

        {children}
  </NotificationProvider>
      </Providers>
        </main>
        </body>
    </html>
  );
}
